# Generated by Django 4.0.6 on 2022-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='image',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
