# Generated by Django 4.0.6 on 2022-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_alter_blogcomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='image',
            field=models.ImageField(default='', upload_to='media/blogger/img'),
        ),
    ]
